export const CHAT_SEND_MESSAGE_REQUEST = 'CHAT_SEND_MESSAGE_REQUEST';
export const CHAT_SEND_MESSAGE_SUCCESS = 'CHAT_SEND_MESSAGE_SUCCESS';
export const CHAT_SEND_MESSAGE_FAIL = 'CHAT_SEND_MESSAGE_FAIL';

export const CHAT_GET_MESSAGES_REQUEST = 'CHAT_GET_MESSAGES_REQUEST';
export const CHAT_GET_MESSAGES_SUCCESS = 'CHAT_GET_MESSAGES_SUCCESS';
export const CHAT_GET_MESSAGES_FAIL = 'CHAT_GET_MESSAGES_FAIL';

export const CHAT_MARK_AS_READ_REQUEST = 'CHAT_MARK_AS_READ_REQUEST';
export const CHAT_MARK_AS_READ_SUCCESS = 'CHAT_MARK_AS_READ_SUCCESS';
export const CHAT_MARK_AS_READ_FAIL = 'CHAT_MARK_AS_READ_FAIL';

export const CHAT_GET_UNREAD_COUNT_REQUEST = 'CHAT_GET_UNREAD_COUNT_REQUEST';
export const CHAT_GET_UNREAD_COUNT_SUCCESS = 'CHAT_GET_UNREAD_COUNT_SUCCESS';
export const CHAT_GET_UNREAD_COUNT_FAIL = 'CHAT_GET_UNREAD_COUNT_FAIL';

export const CHAT_ALL_GET_MESSAGES_REQUEST = 'CHAT_ALL_GET_MESSAGES_REQUEST';
export const CHAT_ALL_GET_MESSAGES_SUCCESS = 'CHAT_ALL_GET_MESSAGES_SUCCESS';
export const CHAT_ALL_GET_MESSAGES_FAIL = 'CHAT_ALL_GET_MESSAGES_FAIL';

export const CHAT_UPDATE_CONVERSATION_STATUS_REQUEST = 'CHAT_UPDATE_CONVERSATION_STATUS_REQUEST';
export const CHAT_UPDATE_CONVERSATION_STATUS_SUCCESS = 'CHAT_UPDATE_CONVERSATION_STATUS_SUCCESS';
export const CHAT_UPDATE_CONVERSATION_STATUS_FAIL = 'CHAT_UPDATE_CONVERSATION_STATUS_FAIL';

export const CHAT_UPDATE_CONVERSATION_PRIORITY_REQUEST = 'CHAT_UPDATE_CONVERSATION_PRIORITY_REQUEST';
export const CHAT_UPDATE_CONVERSATION_PRIORITY_SUCCESS = 'CHAT_UPDATE_CONVERSATION_PRIORITY_SUCCESS';
export const CHAT_UPDATE_CONVERSATION_PRIORITY_FAIL = 'CHAT_UPDATE_CONVERSATION_PRIORITY_FAIL';
