// Event Actions
export const EVENTS_GET_REQUEST = 'EVENTS_GET_REQUEST';
export const EVENTS_GET_SUCCESS = 'EVENTS_GET_SUCCESS';
export const EVENTS_GET_FAIL = 'EVENTS_GET_FAIL';

export const EVENT_MARK_COMPLETE_REQUEST = 'EVENT_MARK_COMPLETE_REQUEST';
export const EVENT_MARK_COMPLETE_SUCCESS = 'EVENT_MARK_COMPLETE_SUCCESS';
export const EVENT_MARK_COMPLETE_FAIL = 'EVENT_MARK_COMPLETE_FAIL';

// Fines Actions
export const FINES_GET_REQUEST = 'FINES_GET_REQUEST';
export const FINES_GET_SUCCESS = 'FINES_GET_SUCCESS';
export const FINES_GET_FAIL = 'FINES_GET_FAIL';

export const FINE_WAIVE_REQUEST = 'FINE_WAIVE_REQUEST';
export const FINE_WAIVE_SUCCESS = 'FINE_WAIVE_SUCCESS';
export const FINE_WAIVE_FAIL = 'FINE_WAIVE_FAIL';
