export const GROUP_CREATE_REQUEST = 'GROUP_CREATE_REQUEST';
export const GROUP_CREATE_SUCCESS = 'GROUP_CREATE_SUCCESS';
export const GROUP_CREATE_FAIL = 'GROUP_CREATE_FAIL';

export const GROUP_LIST_REQUEST = 'GROUP_LIST_REQUEST';
export const GROUP_LIST_SUCCESS = 'GROUP_LIST_SUCCESS';
export const GROUP_LIST_FAIL = 'GROUP_LIST_FAIL';

export const MY_GROUPS_REQUEST = 'MY_GROUPS_REQUEST';
export const MY_GROUPS_SUCCESS = 'MY_GROUPS_SUCCESS';
export const MY_GROUPS_FAIL = 'MY_GROUPS_FAIL';

export const GROUP_DETAILS_REQUEST = 'GROUP_DETAILS_REQUEST';
export const GROUP_DETAILS_SUCCESS = 'GROUP_DETAILS_SUCCESS';
export const GROUP_DETAILS_FAIL = 'GROUP_DETAILS_FAIL';

export const GROUP_UPDATE_REQUEST = 'GROUP_UPDATE_REQUEST';
export const GROUP_UPDATE_SUCCESS = 'GROUP_UPDATE_SUCCESS';
export const GROUP_UPDATE_FAIL = 'GROUP_UPDATE_FAIL';

export const GROUP_ACCOUNTS_UPDATE_REQUEST = 'GROUP_ACCOUNTS_UPDATE_REQUEST';
export const GROUP_ACCOUNTS_UPDATE_SUCCESS = 'GROUP_ACCOUNTS_UPDATE_SUCCESS';
export const GROUP_ACCOUNTS_UPDATE_FAIL = 'GROUP_ACCOUNTS_UPDATE_FAIL';

export const GROUP_TRANSFER_OWNERSHIP_REQUEST = 'GROUP_TRANSFER_OWNERSHIP_REQUEST';
export const GROUP_TRANSFER_OWNERSHIP_SUCCESS = 'GROUP_TRANSFER_OWNERSHIP_SUCCESS';
export const GROUP_TRANSFER_OWNERSHIP_FAIL = 'GROUP_TRANSFER_OWNERSHIP_FAIL';

export const GROUP_ADD_MEMBERS_REQUEST = 'GROUP_ADD_MEMBERS_REQUEST';
export const GROUP_ADD_MEMBERS_SUCCESS = 'GROUP_ADD_MEMBERS_SUCCESS';
export const GROUP_ADD_MEMBERS_FAIL = 'GROUP_ADD_MEMBERS_FAIL';

export const GROUP_UPDATE_MEMBER_REQUEST = 'GROUP_UPDATE_MEMBER_REQUEST';
export const GROUP_UPDATE_MEMBER_SUCCESS = 'GROUP_UPDATE_MEMBER_SUCCESS';
export const GROUP_UPDATE_MEMBER_FAIL = 'GROUP_UPDATE_MEMBER_FAIL';

export const GROUP_REMOVE_MEMBER_REQUEST = 'GROUP_REMOVE_MEMBER_REQUEST';
export const GROUP_REMOVE_MEMBER_SUCCESS = 'GROUP_REMOVE_MEMBER_SUCCESS';
export const GROUP_REMOVE_MEMBER_FAIL = 'GROUP_REMOVE_MEMBER_FAIL';

export const GROUP_LEAVE_REQUEST = 'GROUP_LEAVE_REQUEST';
export const GROUP_LEAVE_SUCCESS = 'GROUP_LEAVE_SUCCESS';
export const GROUP_LEAVE_FAIL = 'GROUP_LEAVE_FAIL';


export const GROUP_DELETE_REQUEST = 'GROUP_DELETE_REQUEST';
export const GROUP_DELETE_SUCCESS = 'GROUP_DELETE_SUCCESS'; 
export const GROUP_DELETE_FAIL = 'GROUP_DELETE_FAIL';

// Public and Invitation Routes

export const GROUP_PUBLIC_LIST_REQUEST = 'GROUP_PUBLIC_LIST_REQUEST';
export const GROUP_PUBLIC_LIST_SUCCESS = 'GROUP_PUBLIC_LIST_SUCCESS';
export const GROUP_PUBLIC_LIST_FAIL = 'GROUP_PUBLIC_LIST_FAIL';

export const GROUP_MY_INVITATIONS_REQUEST = 'GROUP_MY_INVITATIONS_REQUEST';
export const GROUP_MY_INVITATIONS_SUCCESS = 'GROUP_MY_INVITATIONS_SUCCESS';
export const GROUP_MY_INVITATIONS_FAIL = 'GROUP_MY_INVITATIONS_FAIL';

export const GROUP_INVITE_USER_REQUEST = 'GROUP_INVITE_USER_REQUEST';
export const GROUP_INVITE_USER_SUCCESS = 'GROUP_INVITE_USER_SUCCESS';
export const GROUP_INVITE_USER_FAIL = 'GROUP_INVITE_USER_FAIL';

export const GROUP_RESPOND_INVITATION_REQUEST = 'GROUP_RESPOND_INVITATION_REQUEST';
export const GROUP_RESPOND_INVITATION_SUCCESS = 'GROUP_RESPOND_INVITATION_SUCCESS';
export const GROUP_RESPOND_INVITATION_FAIL = 'GROUP_RESPOND_INVITATION_FAIL';


// Join Requests 

export const GROUP_JOIN_REQUEST_REQUEST = 'GROUP_JOIN_REQUEST_REQUEST';
export const GROUP_JOIN_REQUEST_SUCCESS = 'GROUP_JOIN_REQUEST_SUCCESS';
export const GROUP_JOIN_REQUEST_FAIL = 'GROUP_JOIN_REQUEST_FAIL';

export const GROUP_REVIEW_JOIN_REQUEST_REQUEST = 'GROUP_REVIEW_JOIN_REQUEST_REQUEST';
export const GROUP_REVIEW_JOIN_REQUEST_SUCCESS = 'GROUP_REVIEW_JOIN_REQUEST_SUCCESS';
export const GROUP_REVIEW_JOIN_REQUEST_FAIL = 'GROUP_REVIEW_JOIN_REQUEST_FAIL';

export const GROUP_GET_JOIN_REQUESTS_REQUEST = 'GROUP_GET_JOIN_REQUESTS_REQUEST';
export const GROUP_GET_JOIN_REQUESTS_SUCCESS = 'GROUP_GET_JOIN_REQUESTS_SUCCESS';
export const GROUP_GET_JOIN_REQUESTS_FAIL = 'GROUP_GET_JOIN_REQUESTS_FAIL';

export const GROUP_GET_MY_JOIN_REQUESTS_REQUEST = 'GROUP_GET_JOIN_REQUESTS_REQUEST';
export const GROUP_GET_MY_JOIN_REQUESTS_SUCCESS = 'GROUP_GET_JOIN_REQUESTS_SUCCESS';
export const GROUP_GET_MY_JOIN_REQUESTS_FAIL = 'GROUP_GET_JOIN_REQUESTS_FAIL';

// Contributions & Payments

export const GROUP_WALLET_CONTRIBUTION_REQUEST = 'GROUP_WALLET_CONTRIBUTION_REQUEST';
export const GROUP_WALLET_CONTRIBUTION_SUCCESS = 'GROUP_WALLET_CONTRIBUTION_SUCCESS';
export const GROUP_WALLET_CONTRIBUTION_FAIL = 'GROUP_WALLET_CONTRIBUTION_FAIL';

export const GROUP_CASH_CONTRIBUTION_REQUEST = 'GROUP_CASH_CONTRIBUTION_REQUEST';
export const GROUP_CASH_CONTRIBUTION_SUCCESS = 'GROUP_CASH_CONTRIBUTION_SUCCESS';
export const GROUP_CASH_CONTRIBUTION_FAIL = 'GROUP_CASH_CONTRIBUTION_FAIL';

export const GROUP_MOBILE_CONTRIBUTION_REQUEST = 'GROUP_MOBILE_CONTRIBUTION_REQUEST';
export const GROUP_MOBILE_CONTRIBUTION_SUCCESS = 'GROUP_MOBILE_CONTRIBUTION_SUCCESS';
export const GROUP_MOBILE_CONTRIBUTION_FAIL = 'GROUP_MOBILE_CONTRIBUTION_FAIL';

export const GROUP_GET_CONTRIBUTIONS_REQUEST = 'GROUP_GET_CONTRIBUTIONS_REQUEST';
export const GROUP_GET_CONTRIBUTIONS_SUCCESS = 'GROUP_GET_CONTRIBUTIONS_SUCCESS';
export const GROUP_GET_CONTRIBUTIONS_FAIL = 'GROUP_GET_CONTRIBUTIONS_FAIL';

export const GROUP_MEMBER_CONTRIBUTIONS_REQUEST = 'GROUP_MEMBER_CONTRIBUTIONS_REQUEST';
export const GROUP_MEMBER_CONTRIBUTIONS_SUCCESS = 'GROUP_MEMBER_CONTRIBUTIONS_SUCCESS';
export const GROUP_MEMBER_CONTRIBUTIONS_FAIL = 'GROUP_MEMBER_CONTRIBUTIONS_FAIL';

// Wallet & Member Payments

export const GROUP_FUND_WALLET_REQUEST = 'GROUP_FUND_WALLET_REQUEST';
export const GROUP_FUND_WALLET_SUCCESS = 'GROUP_FUND_WALLET_SUCCESS';
export const GROUP_FUND_WALLET_FAIL = 'GROUP_FUND_WALLET_FAIL';

export const GROUP_PAY_MEMBER_REQUEST = 'GROUP_PAY_MEMBER_REQUEST';
export const GROUP_PAY_MEMBER_SUCCESS = 'GROUP_PAY_MEMBER_SUCCESS';
export const GROUP_PAY_MEMBER_FAIL = 'GROUP_PAY_MEMBER_FAIL';

