export const GROUP_CREATE_REQUEST = 'GROUP_CREATE_REQUEST';
export const GROUP_CREATE_SUCCESS = 'GROUP_CREATE_SUCCESS';
export const GROUP_CREATE_FAIL = 'GROUP_CREATE_FAIL';

export const GROUP_LIST_REQUEST = 'GROUP_LIST_REQUEST';
export const GROUP_LIST_SUCCESS = 'GROUP_LIST_SUCCESS';
export const GROUP_LIST_FAIL = 'GROUP_LIST_FAIL';

export const MY_GROUPS_REQUEST = 'MY_GROUPS_REQUEST';
export const MY_GROUPS_SUCCESS = 'MY_GROUPS_SUCCESS';
export const MY_GROUPS_FAIL = 'MY_GROUPS_FAIL';

export const GROUP_DETAILS_REQUEST = 'GROUP_DETAILS_REQUEST';
export const GROUP_DETAILS_SUCCESS = 'GROUP_DETAILS_SUCCESS';
export const GROUP_DETAILS_FAIL = 'GROUP_DETAILS_FAIL';

export const GROUP_UPDATE_REQUEST = 'GROUP_UPDATE_REQUEST';
export const GROUP_UPDATE_SUCCESS = 'GROUP_UPDATE_SUCCESS';
export const GROUP_UPDATE_FAIL = 'GROUP_UPDATE_FAIL';

export const GROUP_ACCOUNTS_UPDATE_REQUEST = 'GROUP_ACCOUNTS_UPDATE_REQUEST';
export const GROUP_ACCOUNTS_UPDATE_SUCCESS = 'GROUP_ACCOUNTS_UPDATE_SUCCESS';
export const GROUP_ACCOUNTS_UPDATE_FAIL = 'GROUP_ACCOUNTS_UPDATE_FAIL';

export const GROUP_TRANSFER_OWNERSHIP_REQUEST = 'GROUP_TRANSFER_OWNERSHIP_REQUEST';
export const GROUP_TRANSFER_OWNERSHIP_SUCCESS = 'GROUP_TRANSFER_OWNERSHIP_SUCCESS';
export const GROUP_TRANSFER_OWNERSHIP_FAIL = 'GROUP_TRANSFER_OWNERSHIP_FAIL';

export const GROUP_ADD_MEMBERS_REQUEST = 'GROUP_ADD_MEMBERS_REQUEST';
export const GROUP_ADD_MEMBERS_SUCCESS = 'GROUP_ADD_MEMBERS_SUCCESS';
export const GROUP_ADD_MEMBERS_FAIL = 'GROUP_ADD_MEMBERS_FAIL';

export const GROUP_UPDATE_MEMBER_REQUEST = 'GROUP_UPDATE_MEMBER_REQUEST';
export const GROUP_UPDATE_MEMBER_SUCCESS = 'GROUP_UPDATE_MEMBER_SUCCESS';
export const GROUP_UPDATE_MEMBER_FAIL = 'GROUP_UPDATE_MEMBER_FAIL';

export const GROUP_REMOVE_MEMBER_REQUEST = 'GROUP_REMOVE_MEMBER_REQUEST';
export const GROUP_REMOVE_MEMBER_SUCCESS = 'GROUP_REMOVE_MEMBER_SUCCESS';
export const GROUP_REMOVE_MEMBER_FAIL = 'GROUP_REMOVE_MEMBER_FAIL';

export const GROUP_LEAVE_REQUEST = 'GROUP_LEAVE_REQUEST';
export const GROUP_LEAVE_SUCCESS = 'GROUP_LEAVE_SUCCESS';
export const GROUP_LEAVE_FAIL = 'GROUP_LEAVE_FAIL';