export const LOAN_CREATE_REQUEST = 'LOAN_CREATE_REQUEST';
export const LOAN_CREATE_SUCCESS = 'LOAN_CREATE_SUCCESS';
export const LOAN_CREATE_FAIL = 'LOAN_CREATE_FAIL';
export const LOAN_CREATE_RESET = 'LOAN_CREATE_RESET';

export const LOAN_LIST_REQUEST = 'LOAN_LIST_REQUEST';
export const LOAN_LIST_SUCCESS = 'LOAN_LIST_SUCCESS';
export const LOAN_LIST_FAIL = 'LOAN_LIST_FAIL';

export const LOAN_DETAILS_REQUEST = 'LOAN_DETAILS_REQUEST';
export const LOAN_DETAILS_SUCCESS = 'LOAN_DETAILS_SUCCESS';
export const LOAN_DETAILS_FAIL = 'LOAN_DETAILS_FAIL';
export const LOAN_DETAILS_RESET = 'LOAN_DETAILS_RESET';

export const LOAN_UPDATE_REQUEST = 'LOAN_UPDATE_REQUEST';
export const LOAN_UPDATE_SUCCESS = 'LOAN_UPDATE_SUCCESS';
export const LOAN_UPDATE_FAIL = 'LOAN_UPDATE_FAIL';
export const LOAN_UPDATE_RESET = 'LOAN_UPDATE_RESET';

export const LOAN_DELETE_REQUEST = 'LOAN_DELETE_REQUEST';
export const LOAN_DELETE_SUCCESS = 'LOAN_DELETE_SUCCESS';
export const LOAN_DELETE_FAIL = 'LOAN_DELETE_FAIL';

export const LOAN_REVIEW_REQUEST = 'LOAN_REVIEW_REQUEST';
export const LOAN_REVIEW_SUCCESS = 'LOAN_REVIEW_SUCCESS';
export const LOAN_REVIEW_FAIL = 'LOAN_REVIEW_FAIL';
export const LOAN_REVIEW_RESET = 'LOAN_REVIEW_RESET';

export const LOAN_DISBURSE_REQUEST = 'LOAN_DISBURSE_REQUEST';
export const LOAN_DISBURSE_SUCCESS = 'LOAN_DISBURSE_SUCCESS';
export const LOAN_DISBURSE_FAIL = 'LOAN_DISBURSE_FAIL';
export const LOAN_DISBURSE_RESET = 'LOAN_DISBURSE_RESET';

export const LOAN_REPAY_REQUEST = 'LOAN_REPAY_REQUEST';
export const LOAN_REPAY_SUCCESS = 'LOAN_REPAY_SUCCESS';
export const LOAN_REPAY_FAIL = 'LOAN_REPAY_FAIL';
export const LOAN_REPAY_RESET = 'LOAN_REPAY_RESET';

export const LOAN_STATISTICS_REQUEST = 'LOAN_STATISTICS_REQUEST';
export const LOAN_STATISTICS_SUCCESS = 'LOAN_STATISTICS_SUCCESS';
export const LOAN_STATISTICS_FAIL = 'LOAN_STATISTICS_FAIL';

// New constants for additional actions
export const LOAN_APPLY_LATE_FEES_REQUEST = 'LOAN_APPLY_LATE_FEES_REQUEST';
export const LOAN_APPLY_LATE_FEES_SUCCESS = 'LOAN_APPLY_LATE_FEES_SUCCESS';
export const LOAN_APPLY_LATE_FEES_FAIL = 'LOAN_APPLY_LATE_FEES_FAIL';
export const LOAN_APPLY_LATE_FEES_RESET = 'LOAN_APPLY_LATE_FEES_RESET';

export const LOAN_DEFAULT_REQUEST = 'LOAN_DEFAULT_REQUEST';
export const LOAN_DEFAULT_SUCCESS = 'LOAN_DEFAULT_SUCCESS';
export const LOAN_DEFAULT_FAIL = 'LOAN_DEFAULT_FAIL';
export const LOAN_DEFAULT_RESET = 'LOAN_DEFAULT_RESET';

export const LOAN_USER_LIST_REQUEST = 'LOAN_USER_LIST_REQUEST';
export const LOAN_USER_LIST_SUCCESS = 'LOAN_USER_LIST_SUCCESS';
export const LOAN_USER_LIST_FAIL = 'LOAN_USER_LIST_FAIL';

export const LOAN_GROUP_LIST_REQUEST = 'LOAN_GROUP_LIST_REQUEST';
export const LOAN_GROUP_LIST_SUCCESS = 'LOAN_GROUP_LIST_SUCCESS';
export const LOAN_GROUP_LIST_FAIL = 'LOAN_GROUP_LIST_FAIL';

export const LOAN_APPLY_REQUEST = 'LOAN_APPLY_REQUEST';
export const LOAN_APPLY_SUCCESS = 'LOAN_APPLY_SUCCESS';
export const LOAN_APPLY_FAIL = 'LOAN_APPLY_FAIL';
export const LOAN_APPLY_RESET = 'LOAN_APPLY_RESET';

export const LOAN_ADD_GUARANTOR_REQUEST = 'LOAN_ADD_GUARANTOR_REQUEST';
export const LOAN_ADD_GUARANTOR_SUCCESS = 'LOAN_ADD_GUARANTOR_SUCCESS';
export const LOAN_ADD_GUARANTOR_FAIL = 'LOAN_ADD_GUARANTOR_FAIL';
export const LOAN_ADD_GUARANTOR_RESET = 'LOAN_ADD_GUARANTOR_RESET';

export const LOAN_GUARANTOR_APPROVAL_REQUEST = 'LOAN_GUARANTOR_APPROVAL_REQUEST';
export const LOAN_GUARANTOR_APPROVAL_SUCCESS = 'LOAN_GUARANTOR_APPROVAL_SUCCESS';
export const LOAN_GUARANTOR_APPROVAL_FAIL = 'LOAN_GUARANTOR_APPROVAL_FAIL';
export const LOAN_GUARANTOR_APPROVAL_RESET = 'LOAN_GUARANTOR_APPROVAL_RESET';

export const LOAN_DOCUMENT_UPLOAD_REQUEST = 'LOAN_DOCUMENT_UPLOAD_REQUEST';
export const LOAN_DOCUMENT_UPLOAD_SUCCESS = 'LOAN_DOCUMENT_UPLOAD_SUCCESS';
export const LOAN_DOCUMENT_UPLOAD_FAIL = 'LOAN_DOCUMENT_UPLOAD_FAIL';
export const LOAN_DOCUMENT_UPLOAD_RESET = 'LOAN_DOCUMENT_UPLOAD_RESET';

export const LOAN_DOCUMENT_REMOVE_REQUEST = 'LOAN_DOCUMENT_REMOVE_REQUEST';
export const LOAN_DOCUMENT_REMOVE_SUCCESS = 'LOAN_DOCUMENT_REMOVE_SUCCESS';
export const LOAN_DOCUMENT_REMOVE_FAIL = 'LOAN_DOCUMENT_REMOVE_FAIL';

export const LOAN_GUARANTOR_LOANS_REQUEST = 'LOAN_GUARANTOR_LOANS_REQUEST';
export const LOAN_GUARANTOR_LOANS_SUCCESS = 'LOAN_GUARANTOR_LOANS_SUCCESS';
export const LOAN_GUARANTOR_LOANS_FAIL = 'LOAN_GUARANTOR_LOANS_FAIL';