// M-Pesa Payment Constants
export const MPESA_PAYMENT_REQUEST = 'MPESA_PAYMENT_REQUEST';
export const MPESA_PAYMENT_SUCCESS = 'MPESA_PAYMENT_SUCCESS';
export const MPESA_PAYMENT_FAIL = 'MPESA_PAYMENT_FAIL';

export const MPESA_QUERY_REQUEST = 'MPESA_QUERY_REQUEST';
export const MPESA_QUERY_SUCCESS = 'MPESA_QUERY_SUCCESS';
export const MPESA_QUERY_FAIL = 'MPESA_QUERY_FAIL';

export const MPESA_WITHDRAWAL_REQUEST = 'MPESA_WITHDRAWAL_REQUEST';
export const MPESA_WITHDRAWAL_SUCCESS = 'MPESA_WITHDRAWAL_SUCCESS';
export const MPESA_WITHDRAWAL_FAIL = 'MPESA_WITHDRAWAL_FAIL';

export const MPESA_WITHDRAWAL_STATUS_REQUEST = 'MPESA_WITHDRAWAL_STATUS_REQUEST';
export const MPESA_WITHDRAWAL_STATUS_SUCCESS = 'MPESA_WITHDRAWAL_STATUS_SUCCESS';
export const MPESA_WITHDRAWAL_STATUS_FAIL = 'MPESA_WITHDRAWAL_STATUS_FAIL';

export const MPESA_BALANCE_REQUEST = 'MPESA_BALANCE_REQUEST';
export const MPESA_BALANCE_SUCCESS = 'MPESA_BALANCE_SUCCESS';
export const MPESA_BALANCE_FAIL = 'MPESA_BALANCE_FAIL';
export const MPESA_PAYMENT_RESET = 'MPESA_PAYMENT_RESET';


export const PAYMENT_STATUS_REQUEST = 'PAYMENT_STATUS_REQUEST';
export const PAYMENT_STATUS_SUCCESS = 'PAYMENT_STATUS_SUCCESS';
export const PAYMENT_STATUS_FAIL = 'PAYMENT_STATUS_FAIL';
export const PAYMENT_STATUS_RESET = 'PAYMENT_STATUS_RESET'

// Stripe Payment Constants
export const STRIPE_PAYMENT_REQUEST = 'STRIPE_PAYMENT_REQUEST';
export const STRIPE_PAYMENT_SUCCESS = 'STRIPE_PAYMENT_SUCCESS';
export const STRIPE_PAYMENT_FAIL = 'STRIPE_PAYMENT_FAIL';
export const STRIPE_PAYMENT_RESET = 'STRIPE_PAYMENT_RESET';

export const STRIPE_PAYMENT_DETAILS_REQUEST = 'STRIPE_PAYMENT_DETAILS_REQUEST';
export const STRIPE_PAYMENT_DETAILS_SUCCESS = 'STRIPE_PAYMENT_DETAILS_SUCCESS';
export const STRIPE_PAYMENT_DETAILS_FAIL = 'STRIPE_PAYMENT_DETAILS_FAIL';

export const STRIPE_PAYOUT_REQUEST = 'STRIPE_PAYOUT_REQUEST';
export const STRIPE_PAYOUT_SUCCESS = 'STRIPE_PAYOUT_SUCCESS';
export const STRIPE_PAYOUT_FAIL = 'STRIPE_PAYOUT_FAIL';

export const STRIPE_PAYOUT_DETAILS_REQUEST = 'STRIPE_PAYOUT_DETAILS_REQUEST';
export const STRIPE_PAYOUT_DETAILS_SUCCESS = 'STRIPE_PAYOUT_DETAILS_SUCCESS';
export const STRIPE_PAYOUT_DETAILS_FAIL = 'STRIPE_PAYOUT_DETAILS_FAIL';

export const STRIPE_BALANCE_REQUEST = 'STRIPE_BALANCE_REQUEST';
export const STRIPE_BALANCE_SUCCESS = 'STRIPE_BALANCE_SUCCESS';
export const STRIPE_BALANCE_FAIL = 'STRIPE_BALANCE_FAIL';