// USER STATEMENT CONSTANTS
export const GET_USER_STATEMENT_REQUEST = 'GET_USER_STATEMENT_REQUEST';
export const GET_USER_STATEMENT_SUCCESS = 'GET_USER_STATEMENT_SUCCESS';
export const GET_USER_STATEMENT_FAIL = 'GET_USER_STATEMENT_FAIL';

export const GET_MY_STATEMENT_REQUEST = 'GET_MY_STATEMENT_REQUEST';
export const GET_MY_STATEMENT_SUCCESS = 'GET_MY_STATEMENT_SUCCESS';
export const GET_MY_STATEMENT_FAIL = 'GET_MY_STATEMENT_FAIL';

// ADMIN REPORTING CONSTANTS
export const GET_ADMIN_TRANSACTIONS_REQUEST = 'GET_ADMIN_TRANSACTIONS_REQUEST';
export const GET_ADMIN_TRANSACTIONS_SUCCESS = 'GET_ADMIN_TRANSACTIONS_SUCCESS';
export const GET_ADMIN_TRANSACTIONS_FAIL = 'GET_ADMIN_TRANSACTIONS_FAIL';

export const GET_ADMIN_ANALYTICS_REQUEST = 'GET_ADMIN_ANALYTICS_REQUEST';
export const GET_ADMIN_ANALYTICS_SUCCESS = 'GET_ADMIN_ANALYTICS_SUCCESS';
export const GET_ADMIN_ANALYTICS_FAIL = 'GET_ADMIN_ANALYTICS_FAIL';

export const GET_REALTIME_METRICS_REQUEST = 'GET_REALTIME_METRICS_REQUEST';
export const GET_REALTIME_METRICS_SUCCESS = 'GET_REALTIME_METRICS_SUCCESS';
export const GET_REALTIME_METRICS_FAIL = 'GET_REALTIME_METRICS_FAIL';

export const GET_FRAUD_INSIGHTS_REQUEST = 'GET_FRAUD_INSIGHTS_REQUEST';
export const GET_FRAUD_INSIGHTS_SUCCESS = 'GET_FRAUD_INSIGHTS_SUCCESS';
export const GET_FRAUD_INSIGHTS_FAIL = 'GET_FRAUD_INSIGHTS_FAIL';

// DATA EXPORT CONSTANTS
export const EXPORT_TRANSACTIONS_REQUEST = 'EXPORT_TRANSACTIONS_REQUEST';
export const EXPORT_TRANSACTIONS_SUCCESS = 'EXPORT_TRANSACTIONS_SUCCESS';
export const EXPORT_TRANSACTIONS_FAIL = 'EXPORT_TRANSACTIONS_FAIL';

export const EXPORT_USER_TRANSACTIONS_REQUEST = 'EXPORT_USER_TRANSACTIONS_REQUEST';
export const EXPORT_USER_TRANSACTIONS_SUCCESS = 'EXPORT_USER_TRANSACTIONS_SUCCESS';
export const EXPORT_USER_TRANSACTIONS_FAIL = 'EXPORT_USER_TRANSACTIONS_FAIL';

// CUSTOM REPORT CONSTANTS
export const GENERATE_CUSTOM_REPORT_REQUEST = 'GENERATE_CUSTOM_REPORT_REQUEST';
export const GENERATE_CUSTOM_REPORT_SUCCESS = 'GENERATE_CUSTOM_REPORT_SUCCESS';
export const GENERATE_CUSTOM_REPORT_FAIL = 'GENERATE_CUSTOM_REPORT_FAIL';

// SCHEDULED REPORTS CONSTANTS
export const SCHEDULE_REPORT_REQUEST = 'SCHEDULE_REPORT_REQUEST';
export const SCHEDULE_REPORT_SUCCESS = 'SCHEDULE_REPORT_SUCCESS';
export const SCHEDULE_REPORT_FAIL = 'SCHEDULE_REPORT_FAIL';

export const GET_SCHEDULED_REPORTS_REQUEST = 'GET_SCHEDULED_REPORTS_REQUEST';
export const GET_SCHEDULED_REPORTS_SUCCESS = 'GET_SCHEDULED_REPORTS_SUCCESS';
export const GET_SCHEDULED_REPORTS_FAIL = 'GET_SCHEDULED_REPORTS_FAIL';

export const UPDATE_SCHEDULED_REPORT_REQUEST = 'UPDATE_SCHEDULED_REPORT_REQUEST';
export const UPDATE_SCHEDULED_REPORT_SUCCESS = 'UPDATE_SCHEDULED_REPORT_SUCCESS';
export const UPDATE_SCHEDULED_REPORT_FAIL = 'UPDATE_SCHEDULED_REPORT_FAIL';

export const DELETE_SCHEDULED_REPORT_REQUEST = 'DELETE_SCHEDULED_REPORT_REQUEST';
export const DELETE_SCHEDULED_REPORT_SUCCESS = 'DELETE_SCHEDULED_REPORT_SUCCESS';
export const DELETE_SCHEDULED_REPORT_FAIL = 'DELETE_SCHEDULED_REPORT_FAIL';

export const GET_SCHEDULED_REPORT_REQUEST = 'GET_SCHEDULED_REPORT_REQUEST';
export const GET_SCHEDULED_REPORT_SUCCESS = 'GET_SCHEDULED_REPORT_SUCCESS';
export const GET_SCHEDULED_REPORT_FAIL = 'GET_SCHEDULED_REPORT_FAIL';

// UTILITY CONSTANTS
export const GET_REPORTS_HEALTH_REQUEST = 'GET_REPORTS_HEALTH_REQUEST';
export const GET_REPORTS_HEALTH_SUCCESS = 'GET_REPORTS_HEALTH_SUCCESS';
export const GET_REPORTS_HEALTH_FAIL = 'GET_REPORTS_HEALTH_FAIL';

export const GET_REPORTS_CONFIG_REQUEST = 'GET_REPORTS_CONFIG_REQUEST';
export const GET_REPORTS_CONFIG_SUCCESS = 'GET_REPORTS_CONFIG_SUCCESS';
export const GET_REPORTS_CONFIG_FAIL = 'GET_REPORTS_CONFIG_FAIL';

// REPORT CLEARING CONSTANTS
export const CLEAR_REPORT_ERRORS = 'CLEAR_REPORT_ERRORS';
export const CLEAR_USER_STATEMENT = 'CLEAR_USER_STATEMENT';
export const CLEAR_MY_STATEMENT = 'CLEAR_MY_STATEMENT';
export const CLEAR_ADMIN_REPORTS = 'CLEAR_ADMIN_REPORTS';
export const CLEAR_CUSTOM_REPORT = 'CLEAR_CUSTOM_REPORT';
export const CLEAR_EXPORT_DATA = 'CLEAR_EXPORT_DATA';
export const CLEAR_SCHEDULED_REPORTS = 'CLEAR_SCHEDULED_REPORTS';

// REPORT LOADING STATES
export const SET_REPORT_LOADING = 'SET_REPORT_LOADING';
export const CLEAR_REPORT_LOADING = 'CLEAR_REPORT_LOADING';