// Get Settings
export const SETTINGS_GET_REQUEST = 'SETTINGS_GET_REQUEST';
export const SETTINGS_GET_SUCCESS = 'SETTINGS_GET_SUCCESS';
export const SETTINGS_GET_FAIL = 'SETTINGS_GET_FAIL';

// Update Settings
export const SETTINGS_UPDATE_REQUEST = 'SETTINGS_UPDATE_REQUEST';
export const SETTINGS_UPDATE_SUCCESS = 'SETTINGS_UPDATE_SUCCESS';
export const SETTINGS_UPDATE_FAIL = 'SETTINGS_UPDATE_FAIL';

// Reset Settings
export const SETTINGS_RESET_REQUEST = 'SETTINGS_RESET_REQUEST';
export const SETTINGS_RESET_SUCCESS = 'SETTINGS_RESET_SUCCESS';
export const SETTINGS_RESET_FAIL = 'SETTINGS_RESET_FAIL';

// Server Info
export const SERVER_INFO_GET_REQUEST = 'SERVER_INFO_GET_REQUEST';
export const SERVER_INFO_GET_SUCCESS = 'SERVER_INFO_GET_SUCCESS';
export const SERVER_INFO_GET_FAIL = 'SERVER_INFO_GET_FAIL';

// Database Info
export const DB_INFO_GET_REQUEST = 'DB_INFO_GET_REQUEST';
export const DB_INFO_GET_SUCCESS = 'DB_INFO_GET_SUCCESS';
export const DB_INFO_GET_FAIL = 'DB_INFO_GET_FAIL';