export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';


export const USER_PROFILE_PICTURE_UPLOAD_REQUEST = 'USER_PROFILE_PICTURE_UPLOAD_REQUEST';
export const USER_PROFILE_PICTURE_UPLOAD_SUCCESS = 'USER_PROFILE_PICTURE_UPLOAD_SUCCESS';
export const USER_PROFILE_PICTURE_UPLOAD_FAIL = 'USER_PROFILE_PICTURE_UPLOAD_FAIL';

// Password Reset
export const USER_PASSWORD_RESET_LINK_REQUEST = 'USER_PASSWORD_RESET_LINK_REQUEST';
export const USER_PASSWORD_RESET_LINK_SUCCESS = 'USER_PASSWORD_RESET_LINK_SUCCESS';
export const USER_PASSWORD_RESET_LINK_FAIL = 'USER_PASSWORD_RESET_LINK_FAIL';

export const USER_PASSWORD_RESET_REQUEST = 'USER_PASSWORD_RESET_REQUEST';
export const USER_PASSWORD_RESET_SUCCESS = 'USER_PASSWORD_RESET_SUCCESS';
export const USER_PASSWORD_RESET_FAIL = 'USER_PASSWORD_RESET_FAIL';

export const SEND_OTP_REQUEST = 'SEND_OTP_REQUEST';
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
export const SEND_OTP_FAIL = 'SEND_OTP_FAIL';

export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAIL = 'VERIFY_OTP_FAIL';

export const RESEND_OTP_REQUEST = 'RESEND_OTP_REQUEST';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const RESEND_OTP_FAIL = 'RESEND_OTP_FAIL';

export const CHECK_VERIFICATION_STATUS_REQUEST = 'CHECK_VERIFICATION_STATUS_REQUEST';
export const CHECK_VERIFICATION_STATUS_SUCCESS = 'CHECK_VERIFICATION_STATUS_SUCCESS';
export const CHECK_VERIFICATION_STATUS_FAIL = 'CHECK_VERIFICATION_STATUS_FAIL';

export const SOCIAL_AUTH_REQUEST = 'SOCIAL_AUTH_REQUEST';
export const SOCIAL_AUTH_SUCCESS = 'SOCIAL_AUTH_SUCCESS';
export const SOCIAL_AUTH_FAIL = 'SOCIAL_AUTH_FAIL';

export const USER_SESSIONS_REQUEST = 'USER_SESSIONS_REQUEST';
export const USER_SESSIONS_SUCCESS = 'USER_SESSIONS_SUCCESS';
export const USER_SESSIONS_FAIL = 'USER_SESSIONS_FAIL';

export const USER_SESSION_REVOKE_REQUEST = 'USER_SESSION_REVOKE_REQUEST';
export const USER_SESSION_REVOKE_SUCCESS = 'USER_SESSION_REVOKE_SUCCESS';
export const USER_SESSION_REVOKE_FAIL = 'USER_SESSION_REVOKE_FAIL';
