export const WALLET_DETAILS_REQUEST = 'WALLET_DETAILS_REQUEST';
export const WALLET_DETAILS_SUCCESS = 'WALLET_DETAILS_SUCCESS';
export const WALLET_DETAILS_FAIL = 'WALLET_DETAILS_FAIL';

export const WALLET_UPDATE_REQUEST = 'WALLET_UPDATE_REQUEST';
export const WALLET_UPDATE_SUCCESS = 'WALLET_UPDATE_SUCCESS';
export const WALLET_UPDATE_FAIL = 'WALLET_UPDATE_FAIL';

export const WALLET_DEPOSIT_REQUEST = 'WALLET_DEPOSIT_REQUEST';
export const WALLET_DEPOSIT_SUCCESS = 'WALLET_DEPOSIT_SUCCESS';
export const WALLET_DEPOSIT_FAIL = 'WALLET_DEPOSIT_FAIL';

export const WALLET_WITHDRAW_REQUEST = 'WALLET_WITHDRAW_REQUEST';
export const WALLET_WITHDRAW_SUCCESS = 'WALLET_WITHDRAW_SUCCESS';
export const WALLET_WITHDRAW_FAIL = 'WALLET_WITHDRAW_FAIL';